### ISSUE TITLE
Adjustable UI font size

### ISSUE THREAD

**Issue by chanaldebol** [JamzTheMan/MapTool#101]
I have a high-resolution monitor, and the font size of some UI elements (title bars, button labels, etc.) render too small for me to read without squinting. I set the chat text size to be readable, but I wish there was also an option to increase the size of UI text.

Adding a UI size/scaling selector (even if it only has coarse "small", "medium", and "large" settings) to the accessibility preferences would allow more flexibility than scaling the entire computer's UI.

I've tried using Windows 10's scaling feature, but the results are sub-optimal; It applies the scaling system-wide, so things like the task bar and the title bars of other applications windows balloon to take up more screen real estate that I'd rather devote to content and my GM's beautifully-constructed maps.

**Comment by Phergus** [comment]
As a workaround, you can use the TinyLAF control panel to create a new default.theme with larger fonts.  That's what I do an my high DPI laptop screen and my desktop screen.  But I am also using the Nerps version that is just the jar file.  I'm not sure where you would have to stick the theme file so that the regular Nerps executable release might find it.

**Comment by JamzTheMan** [comment]
What version of MapTool are you using. With Java 9+ it should be scaling based on OS scale just fine.

**Comment by JamzTheMan** [comment]
@Phergus Do you mean currently using TinyLaf or in the future under new UI?

**Comment by Phergus** [comment]
Using TinyLaF to create a theme as a workaround for the current releases until the FX shift is made.  On my stupidly high resolution laptop the Windows OS scaling just doesn't cut it.  He's probably in the same boat.  Just changing a few font sizes in a theme makes it usable.

**Comment by JamzTheMan** [comment]
I could do that if you have the TinyLaF file, want to attach it to this issue?

**Comment by JamzTheMan** [comment]
I'll reopen and we can test with the workaround until #37 is complete.

**Comment by Phergus** [comment]
Here is the one I use on my desktop.  For me, I'm running the jar file version so I just throw it in the same directory.

[DefaultTheme.zip](https://github.com/JamzTheMan/MapTool/files/2430993/DefaultTheme.zip)

**Comment by JamzTheMan** [comment]
To be clear, I'm not going to adjust those other places as its all getting thrown away as the UI is being redone. If someone else wants to submit a PR within the next month or two with all those changes, I'd probably accept that as well if they are solid.

I will entertain supplying extra theme(s) for tiny laf if possible but that's it for issue otherwise.

**Comment by n2ash** [comment]
Right, more noting where they are for any accessibility/resolution-related adjustments prior to that, as unlike HTMLPane or MessagePanel they can't be overwritten with inline formatting and don't respond to LAF.

**Comment by n2ash** [comment]
As for .theme location on the installed executable release: always to the same folder as the .jar, so far as I know. In my case it's %AppData%\Local\Maptool\app, which I believe is default behavior.

**Comment by Phergus** [comment]
@n2ash You could drop that Theme file I uploaded above to confirm it affects your install.  I don't use the installed version.
