### ISSUE TITLE
Expanding Dice rolls to show Individual dice

### ISSUE THREAD

**Issue by Jyoumon** [JamzTheMan/MapTool#102]
Simple issue, we need expanded dice rolling, its very hard to see individual dice rolls.

Solution: simple, expand the Dice conclusions to show all the dice when rolled.

**Comment by JamzTheMan** [comment]
Does it only do it vial tooltip now?

I'm ok with this change but consideration must be given so this is a new option and doesn't break existing macros.

For instance, I expect [r: str = 3d6] to be a number like "12" and not a string like "4+6+2"

**Comment by kayila** [comment]
I'm going to add it as a new roll option, I think. But even via tool tip it doesn't expand the roll. if you do `[t:3d6+1]` the tool tip will only show the result, not the individual die rolls

**Comment by Phergus** [comment]
Should it just list the dice out as a string?
Is a total needed?
Is this for a particular rule system?
Is it going to work for all dice expressions?
How will it differ from [t: 4d6o]?
Perhaps it should return the dice in a JSON list or take an optional separator and put them in string.

**Comment by JamzTheMan** [comment]
To play devils advocate, would you not just put 1d6+1d6+1d6 if you wanted to see the dice?

But i don't roll dice in chat so i guess 10d10 would be hell to type.

FYI there is a json roll option but it adds and returns results.

**Comment by Phergus** [comment]
I'm assuming this is for a game where you roll a pool of dice, usually based on a stat, where each one can explode so you need to see what the individual dice rolled (and exploded or not).  The total isn't typically used just the best roll or the number of successes.  <shrug>

And now that you mention it the json.rolls macro would probably do everything needed.
http://www.lmwcs.com/rptools/wiki/json.rolls

**Comment by n2ash** [comment]
You could do it with json.rolls or by summing after [c(10):d6], yeah. In an ideal world, there should definitely be a full expansion roll option even (arguably *especially*) for roll types like XdY_dN_, _kN_, etc. where the summed output is sufficiently vague, but considering how MapTool sends dice off to be processed I'm not sure how feasible it would be without moderate-to-major changes to the roll engine.

**Comment by Syndaryl** [comment]
I've had to write macros to set this up with our group because they simply want to see all the dicedice; there may be a certain miss trust of electronic dice. We play GURPS so we need the sum, but my players refused to adopt MapTools until they could see those individual rolls. 

The json.rolls macro didn't exist when i was seeing our framework up, so i ended up having to build an arbitrary number of dice macromacro for damagedamage that would show the sum and the individual rolls. Now i could simplify my macro with it, and will, but we still need it.

I'll note that some game systems have luck mechanics that let you reroll one of the dice - this is not the same as "roll 4d6 drop lowest"  as it is done after the roll, not pre-declared. This is still for summing dice, not dice pool mechanics.

**Comment by JamzTheMan** [comment]
Per the doc (haven't tried) json.rolls still sums up and doesn't return individual dice results?

In any case, i can see where there is a gap in the dice mechanic roll options. Either you can view the individual dice and not get a sum or get a sum and not the individual results.

Also, macro functions are ok but technically, via macro, you can already do this via loops + listAppend (there's an example in the wiki).

So at this point I agree with Kayila and it probably should just be a new roll option (which lets users use it via chat easily). Some research could be done to confirm e: roll option is working as intended or not and there isn't overlap, eg, what is the difference between e: and t:?

It could confuse people if there is an e: and <new roll option> because I would think e: does this.  Also, if we changed e: would that really break existing macros?  Personally I use h: or r: almost exclusively but there are others that build complicated tooltips for chat and frames so no idea how much e: is used and if it break things.  Maybe we can ask in #macro channel and take a pulse?

**Comment by kayila** [comment]
Let me take some time and look into the dice rolling code, I'm sure a
solution can be reached.

**Comment by Phergus** [comment]
I'm sure something can be done.  Just trying to make sure the requirement is well-defined and any impacts to existing uses are considered.

If the only goal is to get a list of the individual dice rolls to the chat window that is one thing.  But if the goal is to get back a list of the individual dice rolls to be further used in a macro that is different.

So for a new Roll Option (not Dice Expression flag) like this:

`[X: foo = 4d6d1 + 1d8e + 2]`

What is the expected chat output and what does **foo** contain?

**Comment by JamzTheMan** [comment]
Absolutely and thanks for the feedback @Phergus, it's always better to have more eyes on these types of discussion (especially since my interaction with dice roles is more macro result orientated and simple 1d20+x type stuff)

And also agree result should still be total (unless you are doing successes) and I've never used the modifiers(?) like o and such really. 

I can see how that is going to get interesting, does the 4d6dl nest the tooltip inside another set of ()'s? (and ya, arg, dislike the 1lL0oO's too)
