### ISSUE TITLE
Moving into VBL zone can momentarily freeze MapTool

### ISSUE THREAD

**Issue by matejdro** [JamzTheMan/MapTool#118]
**Describe the bug**
When pathfinding is enabled, MapTool can momentarily freeze (for couple of seconds) when moving the token into VBL zone

**To Reproduce**
1. Create new blank campaign
2. Enable smart movement ("AI" symbol on the right side of the main toolbar)
3. Place down any token
4. Draw hollow rectangular VBL on the right side of the token (see screenshot)
5. Move the selected token into created VBL zone

**Expected behavior**
Character movement should be smooth and MapTool should not freeze, ever

**Screenshots**
![image](https://user-images.githubusercontent.com/507922/50575571-321c9180-0e01-11e9-8a65-eebee1d0a42a.png)

**MapTool Info**
- Version: 1.4.5.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by JamzTheMan** [comment]
This is a product of the AI feature. The AI is calculating (out to infinity possibly because MapTool has unbounded/infinite map space) trying to find a path. I've added a "timeout" so that if a path is not found within x seconds, it gives up. There is "threading" happening and I have it about as optimized as I can get it for now. At the end of the day, the UI does have to wait for the path to finish and return a result (if any) before it can continue, less dependent macros may fail.

Depending on CPU and PC specs, it may or may not find viable paths in a reasonable time.  If you surround your map in a VBL box, it may also help narrow down it's search parameters.

Note: If you drop a token into solid VBL, it should exit it's results immediately as in that case I know there is no way to reach that location.

For now, this is Working as Designed.
