### ISSUE TITLE
Feature Request: Multiple Images per Token

### ISSUE THREAD

**Issue by dorpond** [JamzTheMan/MapTool#17]
To be able to store multiple token images per token. In addition, have a macro to be able to switch those images.

Having to depend on many tables (or one huge one that they all share) to pull this off is just silly (imagine having 45 RPToks that can change shape).

The way I see it, everything token related should be inside the RPTok, including their multiple images - not externally in tables, that may not even exist in your current campaign..

**Comment by Sereptus** [comment]
I hate to butt in here but it seems to me that disguise macro from AM (I believe) does this. That's what I mainly use it for. Although I have had problems in the past where if I move the original(disguise) token image to a new folder or change the property type of the token the other (disguise) image would not be present on the rptok anymore or for some reason unreadable like the red question mark showing up. I haven't really looked into that bug because it works most of the time. @dorpond Isn't this exactly what you're looking for?

**Comment by JamzTheMan** [comment]
It is but it does require "macro" usage/setup/etc.  I do see merit in this for an easier usage.

FWIW, I *do* support multiple images but only for Herolab tokens. But that means I do have a skeleton in place to show/store/use multiple tokens images.

In fact, I also store large text "assets" (statblocks) as well which is another request of sorts. So I just need to move/expose that stuff and make it generic I think and let my Hero Lab stuff just use those pieces instead...
