### ISSUE TITLE
Templates won't preview at the right location

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#70]
When drawing a template, cone or sphere for instance, the preview pops up after the first click. It's no placed correctly and shifted by one or two grid unit to the left. The size is correct. Once finally placed the template get the actual location right. This is a rather minor issue.

**Comment by JamzTheMan** [comment]
I'm going to need steps to reproduce this, OS, server settings if appropriate.

I'm currently unable to duplicate this issue.

**Comment by bobifle** [comment]
Can't seems to reproduce the issue neither. I suggest to stop wasting on time on this. Probably an "operator" error.

**Comment by JamzTheMan** [comment]
There is another issue open that if you click a token a certain way it moves funky. It may be related. But ya, haven't sat down and reproduce it yet. That's the hard part.

**Comment by bobifle** [comment]
Ok I definitely encountered this bug again. I'm sorry I could not take screenshots at the time and did not really had time to investigate but there's def something funny happening. There's a small cursor, beside the mouse cursor, a black cross that snaps to the grid, it was way off many grid units to the left.

It's also not reproducible from a fresh opened empty campaign. I'll have a look later...

**Comment by RicoTheBold** [comment]
I can both reproduce the issue and disable it at will!  I had a strong suspicion that it was tied to Windows DPI scaling.  Running the current version of Windows 10 (1803), I am typically running my 3840 x 2160 screen at 150% scaling on the "scale and layout" section of the display settings.  When it's set to this, I get the weird issue where the preview of the template is in one place (away from the real cursor location) and then when I finish drawing it, it shows up where my cursor _actually_ was.  There's a bit of margin of error there on the matching the real cursor due to the templates snapping to the corner of the grid, but that's expected.

If I disable the scaling (by setting it to 100%, logging out, and logging back in), the preview matches the final template (again, the preview cursor jumps a little due to the grid snap, but that's normal).  Changing the setting without logging out/logging back in will not change the behavior (which is common for the scaling system in Windows 8 and later).

I didn't bother testing any other scaling ratios; I suspect the problem might not happen with a straight 200% pixel-doubling ratio.
