### ISSUE TITLE
High priority (*) campaign properties referencing a non existing prop crash Maptool

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#85]
MT 1.4.5.0

Technically not a crash but infinite modal dialog windows pop. You're good to kill the process.

Easy to reproduce:
Start Maptool, default empty campaign. Create a token, it should be on the "basic" property type.
Go to the campaign properties, add a new one: 

*Foo: {what_ever_misspelled_prop}

update, click ok, mouse over the token to make the stat sheet pops:  dialogs asking for a value pop constantly, there's no way to get rid of them.
If confirmed, this is rather critical as ppl could loose work/data.

**Comment by JamzTheMan** [comment]
Yea, this is a old outstanding issue from the main repo...

Not sure if I will get to it any time soon. I don't venture into the parser logic much...

**Comment by bobifle** [comment]
Should we forward the issue to the main repo ?

**Comment by JamzTheMan** [comment]
Probably should.

**Comment by Darinth** [comment]
I am investigating. I muddled my way through most of the relevant parser code yesterday, figured out which file is directly responsible for the call to the modal dialog. It's called in MapToolVariableResolver.java at line 225 for all variables that weren't able to otherwise be resolved. Pretty certain minisheet or statsheet are what actually display the results of the variable resolution, but by the time that the variables make it there it looks like they've already been resolved, and my lack of knowledge on the specifics of how java does rendering calls is showing because I wasn't able to figure out yesterday where either minisheet.render or statsheet.render might be getting called from to figure out where I need to go in order to find where the variable resolver is actually be called from.

Should be pretty simple once I figure that out. MapToolVariableResolver.getVariable already has a parameter that is specifically designed to give it information about how to resolve variables. Adding an option to never prompt should be pretty straightforward.

**Comment by Darinth** [comment]
I have a PR in to the main repository to resolve this.
RPTools/MapTool#224
