### ISSUE TITLE
BUG: Grid style lights do not respect grid type

### ISSUE THREAD

**Issue by Syndaryl** [JamzTheMan/MapTool#86]
If your grid is set to hexagons, the GRID style lights are still filling in cells on a square grid

**Comment by Syndaryl** [comment]
(related, the blast templates have the same problem)

**Comment by JamzTheMan** [comment]
Not so much a bug as it is a "didn't get to hexes", sorry. The plan is to get to hexes eventually.

He grid is a PITA and they templates never worked properly on them now do things like drawings...

With that said, another developer is looking at hex grids right now so with any luck they may get some love sooner rather than later.
