### ISSUE TITLE
Move "Players Receive Campaign ..." setting to preferences

### ISSUE THREAD

**Issue by WispOfTheWinds** [JamzTheMan/MapTool#89]
The "Players Receive Campaign ..." setting only appears in the options for starting the server and is hard to find and easy to forget about. It would be nice to have this appear in the Preferences somewhere so it can be found more easily.

**Comment by JamzTheMan** [comment]
I don't think I agree with this personally. Some people run multiple games and for some games they may want campaign macros and some they do not. Changing in server settings is easier then remembering toi go into the normal Preferences. There are only 9 or so "server settings" and is less "buried" than it would be if it were in Edit -> Preferences. As soon as I changed this I would get several issues opened that the option is now missing! 😄 

Now a case could be made to add it to the "Campaign Properties" though. But I'd rather take this sort of request to the larger community.

Please open this to the main repo, https://github.com/RPTools/maptool and it can be discussed further.

**Comment by wwmoraes** [comment]
I'll just throw in my two cents.

> I don't think I agree with this personally.

I'm totally with Jamz. This is a server setting, so it should stay in the server setup.

> Now a case could be made to add it to the "Campaign Properties" though.

Also good point Jamz: a Server tab in the Campaign Properties with sticky settings that preload on the server setup would speed up the start of sessions and prevent configuration mistakes. It's a win-win.

**Comment by JamzTheMan** [comment]
FYI: @Azhrei does have a good idea of redoing the server settings with more of a Wizard set of screens so we will probably revisit all of the settings when we go to FX and have better UI options. #soon

**Comment by Azhrei** [comment]
There's also the issue of synchronicity.  The main reason the campaign macros are currently in the server settings is that there was nothing in place for them to remain synchronized across clients when a change occurs, so putting them into the server settings meant they would be pushed out once when the clients connect.  One and done, as they say.

As @JamzTheMan says, there are certainly arguments for changing this implementation.  Those with experience in MTscript know that using Lib: tokens is a better technique, in general.  Those without such experience likely won't be using macros anyway, and even if they are, they'll be simple ones such that the current scheme works fine.

As @wwmoraes says, a _Campaign Properties_ setting that is used as default values for the Start a Server dialog is a great idea.  I love it!

Right now, MT has a bit of a problem because some things you want to set at server start and other things you want to persist with the campaign, but which is which can change for every MT session, particularly if sometimes you're the GM and sometimes you're a player. 🙁  I have a long-term plan to refactor all of those various options and settings.  Anything that was "sometimes this way and sometimes that way" would be put into a third category, so there would be campaign properties, server settings, and <unnamed>.  But that's long-term...

**Comment by wwmoraes** [comment]
> Right now, MT has a bit of a problem because some things you want to set at server start and other things you want to persist with the campaign, but which is which can change for every MT session, particularly if sometimes you're the GM and sometimes you're a player.

@Azhrei, another two cents: Under the _Campain Properties_ > _Server_ tab, instead of simply replicating the server settings, allow the creation of _Server Profiles_. That way, users can create a "GM", "User", "Group 1", "Group 2" and whatever other profiles they might need. And at the _Start a Server_ dialog, add a dropdown menu to choose which profile to preload.

PS.: Sorry if I'm opiniating too much, but I'm not a Java lover to help make those changes myself (if approved) 😥

**Comment by Azhrei** [comment]
We haven’t fonsidered that idea exactly (although it has merits), but we have considered setting up “server configurations” that can be exported, then loaded automatically at startup so that MT would immediately start the server.  This was in support of headless operation (i.e. no display device, like on a remote web server).

We’ll definitely need to think about the overall structure.  Campaign properties obviously aren’t available until a campaign is loaded but we want to be able to start a server before that (to support having a player start the server then a remote GM loading the campaign).

As JavaFX gets rolled into MT, we’ll be rethinking all of this.  Thanks for the input.
