### ISSUE TITLE
Unset Properties in Macro causes modal dialog prompt

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#96]
Although an indicator that a macro is using an undefined Property, if used in a loop it can cause annoyance and possible near endless loop.

**Possible fixes:**
- [ ] Make dialog non-modal, user could at least save campaign/work.
- [ ] Add checkbox to dialog such as "Don't ask again" which defaults all properties to 0
- [ ] Add button to dialog such as "Cancel" which either cancels the running macro or defaults props to 0
- [ ] Completely remove dialog, rely on chat message to alert user of an issue such as "UNSET VARIABLE VALUE"

**Comment by JamzTheMan** [comment]
Good point.  This fix should encompass the statsheet and fix it as well (as it should be calling the same parser logic)

If statsheet needs special handling and needs another issue we can create one but I doubt it will be needed (unless I'm missing a use case)

I for one dread the stat sheet lockup and turn it off (and don't use it much anymore because of it)

**Comment by Darinth** [comment]
Damn. I was looking into your branch specifically in hopes that maybe this one error, which has caused more lockups than any other single issue in all of maptool (actually, possibly more than every other issue in all of maptool combined) for myself and my group, was fixed. Still, it's got a lot of other cool changes. Looking forward to this being fixed. The stat sheet is one of the most useful features for myself and my group, but maptool locking up because of a typo in a calculated property is a real hassle. <3
